walkmod-imports-cleaner-plugin
==============================
Raquel Pau <raquelpau@gmail.com>

image:https://travis-ci.org/rpau/walkmod-imports-cleaner-plugin.svg?branch=master["Build Status", link="https://travis-ci.org/rpau/walkmod-imports-cleaner-plugin"]

This is a walkmod plugin to remove unused imports in Java source files. It does not remove static or wildcard imports.

== Usage
1) Verify that your walkmod version is > = 2.0

2) You can apply walkmod-imports-cleaner-plugin via  http://www.walkmod.com[walkmod] You just need to add the transformation tag in 
your `${PROJECT}/walkmod.xml` file. 

```XML
<!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD"  "http://www.walkmod.com/dtd/walkmod-1.1.dtd" >
<walkmod>
  <transformation type="imports-cleaner" />
</walkmod>
```
Remember, by default, walkmod takes your source files from your `src/main/java` directory. So, if you need to change it, specify a reader 
before the transformation tag with your source directory.
```XML
<reader path="YOUR_SRC_DIR">
```

You can apply walkmod-imports-cleaner-plugin via walkmod. 

  $ walkmod apply

Or, you can also check which would be the modified classes typing:

  $ walkmod check

== Contributing

If you want to hack on this, fork it, improve it and send me a pull request.

To get started using it, just clone it and call mvn install. 


